apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.configs.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_USER: {{ .Values.configs.MYSQL_USER | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.configs.MYSQL_PASSWORD | b64enc | quote }}
